remove changes to signum stuff

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -220,7 +220,7 @@ Influential environment variables:
   ASCIIDOC, ASCIIDOCFLAGS, ASCIIDOCATTRS, A2X, A2XFLAGS,
   INSTALL, INSTALL_PROGRAM, INSTALL_DATA, INSTALL_DIR,
   CTAGS, CTAGSARGS, ETAGS, ETAGSARGS, CSCOPE, CSCOPEARGS,
-  YASH_GETCWD_AUTO_MALLOC, OS, ARCH
+  YASH_GETCWD_AUTO_MALLOC, OS
 END
     exit
 fi
@@ -415,52 +415,33 @@ if [ -n "$OS" ]; then
     ostype="$OS"
 elif $cross_compiling; then
     if [ -n "$host" ]; then
-        for signum in *-signum.h
+        # this list will probably be good enough for 99% of people cross
+        # compiling, the remaining people can just define $OS
+        for os in linux darwin serenity cygwin aix haiku solaris minix
         do
-            signum="${signum%-signum.h}"
             case "$host" in
-                *"$signum"*)
-                    ostype="$signum"
+                *"$os"*)
+                    ostype="$os"
                     break
             esac
         done
     fi
     if [ -z "$ostype" ]; then
-        printf 'Could not determine the target operating system!\n' >&2
-        printf 'Your target might not have a premade signum.h.\n' >&2
-        printf "If this is the case you'll need to generate one yourself by compiling and running makesignum.c on your target." >&2
-        printf "Rename your signum.h to '<os>-signum.h' and place it in the root of the source directory.\n" >&2
-        printf "If this is not the case you'll need to define the \$OS environment variable and re-run configure.\n" >&2
-        fail
+        case $host in
+            *bsd*) # theres like a million different BSDs and I don't wanna list them all in the os list
+                remove="${host%%bsd*}"
+                ostype="${host#"${remove%-*}"-}"
+                ostype="${ostype%"${ostype#*bsd}"}"
+                ;;
+            *)
+                printf 'Could not determine the target operating system!\n' >&2
+                printf "You'll need to define the \$OS environment variable and re-run configure.\n" >&2
+                fail
+                ;;
+        esac
     fi
 else
     ostype=$(uname -s | tr "[:upper:]" "[:lower:]")
-fi
-
-if $cross_compiling; then
-    if [ "$ostype" = "linux" ]; then
-        if [ -n "$ARCH" ]; then
-            arch="$ARCH"
-        elif [ -n "$host" ]; then
-            arch="${host%%-*}"
-        else
-            printf 'Could not determine the target architecture!\n' >&2
-            printf 'You must either use the --host option to configure or define the $ARCH environment variable.\n' >&2
-            fail
-        fi
-        cross_signum="$ostype-$arch-signum.h"
-    else
-        cross_signum="$ostype-signum.h"
-    fi
-
-    if [ -f "cross/$cross_signum" ]; then
-        cp "cross/$cross_signum" cross-signum.h
-    else
-        printf 'Could not find a signum.h for your target!\n' >&2
-        printf "You'll need to generate one yourself by compiling and running makesignum.c on your target.\n" >&2
-        printf "Rename your signum.h to %s and place it in the 'cross' directory.\n" "'$cross_signum'" >&2
-        fail
-    fi
 fi
 
 checked "${ostype}"
