yash: configure: REFACTOR
git-svn-id: svn+ssh://svn.sourceforge.jp/svnroot/yash/yash/trunk@1552 048f04df-13f5-43d7-8114-9f9ceecaec24

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -41,6 +41,7 @@ builtin_objs=""
 builtins_archive="builtins.a"
 lineedit_archive="lineedit.a"
 
+# object files that are optionaly linked
 alias_objs="alias.o"
 history_objs="history.o"
 printf_objs="printf.o"
@@ -132,7 +133,7 @@ done
 
 if [ x"${help}" = x"yes" ]
 then
-    cat <<END
+    exec cat <<END
 Usage: ./configure [options...]
 
 Available options:
@@ -192,31 +193,34 @@ exec 6>"${configh}"
     echo
     date
     echo
-    echo "# Invocation command line was:"
-    echo "%" $(for i in "$0" "$@"; do echo "$i"; done | sed -e '
-    /[^[:alnum:]./=-]/ {
-    s/'"'"'/'"'\\''"'/g
-    s/\(.*\)/'"'"'\1'"'"'/
-    }')
+    printf '# Invocation command line was:\n%%'
+    for i in "$0" "$@"
+    do
+	printf ' %s' "$(printf '%s\n' "$i" |
+	    sed -e '/[^[:alnum:]./=-]/ {
+	    s/'"'"'/'"'\\''"'/g
+	    s/\(.*\)/'"'"'\1'"'"'/
+	    }')"
+    done
     echo
-    echo "#" uname -n = "$(uname -n)"
-    echo "#" uname -m = "$(uname -m)"
-    echo "#" uname -r = "$(uname -r)"
-    echo "#" uname -s = "$(uname -s)"
-    echo "#" uname -v = "$(uname -v)"
     echo
-    echo "#" PATH="${PATH}"
+    printf '# uname -n = %s\n' "$(uname -n)"
+    printf '# uname -m = %s\n' "$(uname -m)"
+    printf '# uname -r = %s\n' "$(uname -r)"
+    printf '# uname -s = %s\n' "$(uname -s)"
+    printf '# uname -v = %s\n' "$(uname -v)"
+    echo
+    printf '# PATH=%s\n' "$PATH"
     echo
     "${havecache}" && echo "#" cache available
     echo
 } >&5
 
-echo "/* ${configh##*/}: generated by configure */" >&6
+printf '/* %s: generated by configure */\n' "${configh##*/}" >&6
 
 checking () {
-    printf "checking %s... " "$1"
-    echo >&5
-    echo "# checking $1..." >&5
+    printf 'checking %s... ' "$1"
+    printf '\nchecking %s...\n' "$1" >&5
     if [ $# -ge 2 ]
     then
 	cachekey="$2"
@@ -233,22 +237,23 @@ getcache () {
     if cacheentry="$(grep -F "${cachekey}	" "${configcache}")"
     then
 	checkresult="${cacheentry#*	}"
-	printf "(cached) "
-	printf "# cache found: key=${cachekey} value=${checkresult}\n" >&5
+	printf '(cached) '
+	printf '# cache found: key=%s value=%s\n' \
+	    "${cachekey}" "${checkresult}" >&5
     else
 	unset cacheentry
 	return 1
     fi
 }
 checkby () {
-    echo "%" "$@" >&5
-    eval "$@" >&5 2>&1
+    printf '%% %s\n' "$*" >&5
+    "$@" >&5 2>&1
     laststatus=$?
     if [ ${laststatus} -eq 0 ]
     then
 	checkresult="yes"
     else
-	echo "# exit status: ${laststatus}" >&5
+	printf '# exit status: %d\n' "${laststatus}" >&5
 	checkresult="no"
 	return ${laststatus}
     fi
@@ -271,21 +276,22 @@ checked () {
     then
 	checkresult="$1"
     fi
-    echo "${checkresult}"
-    echo "# result: ${checkresult}" >&5
+    printf '%s\n' "${checkresult}"
+    printf '# result: %s\n' "${checkresult}" >&5
     if [ x"${cachekey+set}" = x"set" ] && [ x"${cacheentry+set}" != x"set" ]
     then
 	printf "%s\t%s\n" "${cachekey}" "${checkresult}" >&4
     fi
 }
 defconfigh () {
-    echo "#define" $1 ${2-1} >&6
-    echo "# defining $1='${2-1}' in ${configh}" >&5
+    printf '# defining %s=%s in %s\n' "$1" "${2-1}" "${configh}" >&5
+    printf '#define %s %s\n' "$1" "${2-1}" >&6
 }
 fail () {
     echo "configuration failed" >&2
     exit 1
 }
+
 
 cc="${CC:-c99}"
 cflags="${CFLAGS--O1 -g}"
@@ -294,8 +300,9 @@ ldlibs="${LDLIBS--lm}"
 ar="${AR:-ar}"
 arflags="${ARFLAGS--rc}"
 
+
 # check OS type
-checking "operating system"
+checking 'operating system'
 ostype=$(uname -s | tr "[:upper:]" "[:lower:]")
 checked "${ostype}"
 case "${ostype}" in
@@ -304,8 +311,9 @@ case "${ostype}" in
 	;;
 esac
 
+
 # check POSIX conformance
-checking "POSIX conformance"
+checking 'POSIX conformance'
 posix=$(getconf _POSIX_VERSION 2>/dev/null)
 if [ -n "${posix}" ] && [ x"${posix}" != x"undefined" ]
 then
@@ -316,14 +324,13 @@ then
 	posix=""
     fi
 else
-    posix=""
     checked "no"
+    posix=""
 fi
 
-# check SUS conformance
 if [ -n "${posix}" ]
 then
-    checking "SUS conformance"
+    checking 'SUS conformance'
     xopen=$(getconf _XOPEN_VERSION 2>/dev/null)
     if [ -n "${xopen}" ] && [ x"${xopen}" != x"undefined" ]
     then
@@ -334,16 +341,18 @@ then
 	    xopen=""
 	fi
     else
-	xopen=""
 	checked "no"
+	xopen=""
     fi
 fi
 
-# determine the compiler and its flags
+
+# check if gcc is available if the debug option is enabled
 if [ x"${debug}" = x"yes" ]
 then
-    checking "whether GCC is available"
-    if checkby "${CC:-gcc} --version | grep -i gcc"
+    if
+	checking 'whether GCC is available'
+	checkby eval "${CC:-gcc} --version | grep -i gcc"
     then
 	checked "yes"
 	gcc="yes" cc="${CC:-gcc}"
@@ -359,18 +368,20 @@ then
     defconfigh "NDEBUG"
 fi
 
+
 # check if the compiler works
-checking "whether the compiler works"
-cat >"${tempsrc}" <<END
+if
+    checking 'whether the compiler works'
+    cat >"${tempsrc}" <<END
 int main() { return 0; }
 END
-if trymake && tryexec
+    trymake && tryexec
 then
     checked "yes"
 else
     checked "no"
-    echo "Compiler '$cc' is not found or not working." >&2
-    if [ x"$cc" = x"c99" ]
+    printf 'Compiler "%s" is not found or not working.\n' "${cc}" >&2
+    if [ x"${cc}" = x"c99" ]
     then
 	echo "If you have gcc, try: ./configure CC='gcc -std=c99'" >&2
     fi
@@ -380,13 +391,14 @@ fi
 # check if the compiler accepts the -O2 option if we are not debugging
 if [ x"${debug}" = x"no" ]
 then
-    checking "whether the compiler accepts -O2 flag"
-    cat >"${tempsrc}" <<END
+    if
+	checking 'whether the compiler accepts -O2 flag'
+	savecflags=${cflags}
+	cflags="-O2 -g"
+	cat >"${tempsrc}" <<END
 int main() { return 0; }
 END
-    savecflags=${cflags}
-    cflags="-O2 -g"
-    if trycompile
+	trycompile
     then
 	checked "yes"
     else
@@ -396,11 +408,17 @@ END
     unset savecflags
 fi
 
+
 # check if terminfo is available
 if [ x"${enable_lineedit}" = x"yes" ]
 then
-    checking "for terminfo library" terminfo
-    cat >"${tempsrc}" <<END
+    checking 'for terminfo library' terminfo
+    saveldlibs="${ldlibs}"
+    if getcache
+    then
+	checked
+    elif
+	cat >"${tempsrc}" <<END
 #define _POSIX_C_SOURCE ${posix:-1}L
 #define _XOPEN_SOURCE   ${xopen:-1}
 #define _XOPEN_SOURCE_EXTENDED 1
@@ -415,28 +433,22 @@ tputs(tigetstr(""), 1, putchar);
 del_curterm(cur_term);
 }
 END
-    saveldlibs="${ldlibs}"
-    if getcache
+	trymake
     then
-	checked
+	checked "yes"
     else
-	if trymake
-	then
-	    checked "yes"
-	else
-	    for lib in tinfo curses ncurses
-	    do
-		ldlibs="${saveldlibs} -l${lib}"
-		if trymake
-		then
-		    checked "with -l${lib}"
-		    break
-		fi
-	    done
-	    if [ x"${checkresult}" = x"no" ]
+	for lib in tinfo curses ncurses
+	do
+	    ldlibs="${saveldlibs} -l${lib}"
+	    if trymake
 	    then
-		checked
+		checked "with -l${lib}"
+		break
 	    fi
+	done
+	if [ x"${checkresult}" = x"no" ]
+	then
+	    checked
 	fi
     fi
     case "${checkresult}" in
@@ -456,209 +468,191 @@ END
     esac
 fi
 
+
 # check whether system has /proc/self/exe or similar utility file
-checking "for /proc/self/exe"
-if [ -x /proc/self/exe ]
+if
+    checking 'for /proc/self/exe'
+    [ -x /proc/self/exe ]
 then
     checked "yes"
     defconfigh "HAVE_PROC_SELF_EXE"
-else
+elif
     checked "no"
 
-    checking "for /proc/curproc/file"
-    if [ -x /proc/curproc/file ]
-    then
-	checked "yes"
-	defconfigh "HAVE_PROC_CURPROC_FILE"
-    else
-	checked "no"
+    checking 'for /proc/curproc/file'
+    [ -x /proc/curproc/file ]
+then
+    checked "yes"
+    defconfigh "HAVE_PROC_CURPROC_FILE"
+elif
+    checked "no"
 
-	checking "for /proc/\$\$/object/a.out"
-	if [ -x /proc/$$/object/a.out ]
-	then
-	    checked "yes"
-	    defconfigh "HAVE_PROC_OBJECT_AOUT"
-	else
-	    checked "no"
-	fi
-    fi
+    checking 'for /proc/$$/object/a.out'
+    [ -x /proc/$$/object/a.out ]
+then
+    checked "yes"
+    defconfigh "HAVE_PROC_OBJECT_AOUT"
+else
+    checked "no"
 fi
 
+
 # check for strnlen
-checking "for strnlen" strnlen
-if
-    if getcache
-    then
-	[ x"${checkresult}" = x"yes" ]
-    else
-	cat >"${tempsrc}" <<END
+checking 'for strnlen' strnlen
+if ! getcache
+then
+    cat >"${tempsrc}" <<END
 #define _POSIX_C_SOURCE ${posix:-1}L
 #define _XOPEN_SOURCE   ${xopen:-1}
 #include <stddef.h>
 size_t strnlen(const char*, size_t);
 int main() { return strnlen("12345", 3) != 3; }
 END
-	trymake && tryexec
-    fi
+    trymake && tryexec
+fi
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     defconfigh "HAVE_STRNLEN"
 fi
-checked
 
 # check for wcsnlen
-checking "for wcsnlen" wcsnlen
-if
-    if getcache
-    then
-	[ x"${checkresult}" = x"yes" ]
-    else
-	cat >"${tempsrc}" <<END
+checking 'for wcsnlen' wcsnlen
+if ! getcache
+then
+    cat >"${tempsrc}" <<END
 #define _POSIX_C_SOURCE ${posix:-1}L
 #define _XOPEN_SOURCE   ${xopen:-1}
 #include <stddef.h>
 size_t wcsnlen(const wchar_t*, size_t);
 int main() { return wcsnlen(L"12345", 3) != 3; }
 END
-	trymake && tryexec
-    fi
+    trymake && tryexec
+fi
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     defconfigh "HAVE_WCSNLEN"
 fi
-checked
 
 # check for wcwidth
-checking "for wcwidth" wcwidth
-if
-    if getcache
-    then
-	[ x"${checkresult}" = x"yes" ]
-    else
-	cat >"${tempsrc}" <<END
+checking 'for wcwidth' wcwidth
+if ! getcache
+then
+    cat >"${tempsrc}" <<END
 #define _XOPEN_SOURCE ${xopen:-1}
 #include <wchar.h>
 int main() { return wcwidth(L'\0'); }
 END
-	trymake && tryexec
-    fi
+    trymake && tryexec
+fi
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     defconfigh "HAVE_WCWIDTH"
 fi
-checked
 
 # check if sys/stat.h defines S_ISVTX
-checking "if <sys/stat.h> defines S_ISVTX" S_ISVTX
-if
-    if getcache
-    then
-	[ x"${checkresult}" = x"yes" ]
-    else
-	cat >"${tempsrc}" <<END
+checking 'if <sys/stat.h> defines S_ISVTX' S_ISVTX
+if ! getcache
+then
+    cat >"${tempsrc}" <<END
 #define _POSIX_C_SOURCE ${posix:-1}L
 #define _XOPEN_SOURCE   ${xopen:-1}
 #include <sys/stat.h>
 int main() { return S_ISVTX & 0; }
 END
-	trymake
-    fi
+    trymake
+fi
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     defconfigh "HAVE_S_ISVTX"
 fi
-checked
 
 # check if WCONTINUED and WIFCONTINUED are available
-checking "for WCONTINUED and WIFCONTINUED" WCONTINUED
-if
-    if getcache
-    then
-	[ x"${checkresult}" = x"yes" ]
-    else
-	cat >"${tempsrc}" <<END
+checking 'for WCONTINUED and WIFCONTINUED' WCONTINUED
+if ! getcache
+then
+    cat >"${tempsrc}" <<END
 #define _POSIX_C_SOURCE ${posix:-1}L
 #define _XOPEN_SOURCE   ${xopen:-1}
 #include <errno.h>
 #include <sys/wait.h>
 static int s;
 int main() {
-    return waitpid(-1, &s, WNOHANG|WCONTINUED) < 0 && errno == EINVAL;
-    WIFCONTINUED(s);
+return waitpid(-1, &s, WNOHANG|WCONTINUED) < 0 && errno == EINVAL;
+WIFCONTINUED(s);
 }
 END
-	trymake && tryexec
-    fi
+    trymake && tryexec
+fi
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     defconfigh "HAVE_WCONTINUED"
 fi
-checked
 
 # check for eaccess
-checking "for eaccess" eaccess
-if
-    if getcache
-    then
-	[ x"${checkresult}" = x"yes" ]
-    else
-	cat >"${tempsrc}" <<END
+checking 'for eaccess' eaccess
+if ! getcache
+then
+    cat >"${tempsrc}" <<END
 #define _POSIX_C_SOURCE ${posix:-1}L
 #define _XOPEN_SOURCE   ${xopen:-1}
 #include <unistd.h>
 extern int eaccess(const char *, int);
 int main() { (void) eaccess(".", F_OK | R_OK | W_OK | X_OK); }
 END
-	trymake
-    fi
+    trymake
+fi
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     defconfigh "HAVE_EACCESS"
 fi
-checked
 
 # check for strsignal
-checking "for strsingal" strsignal
-if
-    if getcache
-    then
-	[ x"${checkresult}" = x"yes" ]
-    else
-	cat >"${tempsrc}" <<END
+checking 'for strsingal' strsignal
+if ! getcache
+then
+    cat >"${tempsrc}" <<END
 #define _POSIX_C_SOURCE ${posix:-1}L
 #define _XOPEN_SOURCE   ${xopen:-1}
 #include <signal.h>
 extern char *strsignal(int);
 int main() { (void) strsignal(SIGKILL); }
 END
-	trymake
-    fi
+    trymake
+fi
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     defconfigh "HAVE_STRSIGNAL"
 fi
-checked
 
 # check for paths.h
-checking "for paths.h" paths.h
-if
-    if getcache
-    then
-	[ x"${checkresult}" = x"yes" ]
-    else
-	cat >"${tempsrc}" <<END
+checking 'for paths.h' paths.h
+if ! getcache
+then
+    cat >"${tempsrc}" <<END
 #include <paths.h>
 #include <stdio.h>
 int main() { printf("%s\n", _PATH_BSHELL); }
 END
-	trycompile
-    fi
+    trycompile
+fi
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     defconfigh "HAVE_PATHS_H"
 fi
-checked
 
 # check if getcwd accepts (NULL,0) as argument
 checking "if getcwd(NULL,0) returns malloc'ed string" getcwd:automalloc
-if
-    if getcache
-    then
-	[ x"${checkresult}" = x"yes" ]
-    else
-	cat >"${tempsrc}" <<END
+if ! getcache
+then
+    cat >"${tempsrc}" <<END
 #define _POSIX_C_SOURCE ${posix:-1}L
 #define _XOPEN_SOURCE   ${xopen:-1}
 #include <errno.h>
@@ -691,22 +685,20 @@ int main(void) {
     free(wd11); free(wd2); return 0;
 }
 END
-	trymake && tryexec
-    fi
+    trymake && tryexec
+fi
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     defconfigh "GETCWD_AUTO_MALLOC"
 fi
-checked
 
 # check if ioctl supports TIOCGWINSZ
 if [ x"${enable_lineedit}" = x"yes" ]; then
-    checking "if ioctl supports TIOCGWINSZ" TIOCGWINSZ
-    if
-	if getcache
-	then
-	    [ x"${checkresult}" = x"yes" ]
-	else
-	    cat >"${tempsrc}" <<END
+    checking 'if ioctl supports TIOCGWINSZ' TIOCGWINSZ
+    if ! getcache
+    then
+	cat >"${tempsrc}" <<END
 #include <sys/ioctl.h>
 int main() {
     struct winsize ws;
@@ -714,22 +706,20 @@ int main() {
     (void) ws.ws_row, (void) ws.ws_col;
 }
 END
-	    trymake
-	fi
+	trymake
+    fi
+    checked
+    if [ x"${checkresult}" = x"yes" ]
     then
 	defconfigh "HAVE_TIOCGWINSZ"
     fi
-    checked
 fi
 
 # check if wide-oriented I/O is working
-checking "if wide-oriented I/O is fully working" wideio:working
-if
-    if getcache
-    then
-	[ x"${checkresult}" = x"yes" ]
-    else
-	cat >"${tempsrc}" <<END
+checking 'if wide-oriented I/O is fully working' wideio:working
+if ! getcache
+then
+    cat >"${tempsrc}" <<END
 #include <stdio.h>
 #include <wchar.h>
 #define LEN 12345
@@ -765,14 +755,13 @@ int main(void)
     return 0;
 }
 END
-	trymake && tryexec
-    fi
-then
-    :
-else
-    defconfigh "WIO_BROKEN"
+    trymake && tryexec
 fi
 checked
+if [ x"${checkresult}" = x"no" ]
+then
+    defconfigh "WIO_BROKEN"
+fi
 
 echo >&5
 
@@ -838,12 +827,9 @@ fi
 if [ x"$enable_ulimit" = x"yes" ]
 then
     checking "for getrlimit and setrlimit" getrlimit_setrlimit
-    if
-	if getcache
-	then
-	    [ x"${checkresult}" = x"yes" ]
-	else
-	    cat >"${tempsrc}" <<END
+    if ! getcache
+    then
+	cat >"${tempsrc}" <<END
 #define _XOPEN_SOURCE ${xopen:-1}
 #include <sys/resource.h>
 int main() {
@@ -855,15 +841,18 @@ getrlimit(RLIMIT_FSIZE, &l);
 setrlimit(RLIMIT_FSIZE, &l);
 }
 END
-	    trymake
-	fi
+	trymake
+    fi
+    checked
+    if [ x"${checkresult}" = x"yes" ]
     then
 	defconfigh "YASH_ENABLE_ULIMIT"
 	builtin_objs="$builtin_objs $ulimit_objs"
     else
+	printf 'getrlimit/setrlimit unavailable: '\
+	    'the ulimit builtin is disabled\n' >&2
 	enable_ulimit="no"
     fi
-    checked
 fi
 
 # check for RLIMIT_***
@@ -872,43 +861,44 @@ then
     for i in LOCKS MEMLOCK MSGQUEUE NICE NPROC RSS RTPRIO SIGPENDING
     do
 	checking "for RLIMIT_${i}" "RLIMIT_${i}"
-	if
-	    if getcache
-	    then
-		[ x"${checkresult}" = x"yes" ]
-	    else
-		cat >"${tempsrc}" <<END
+	if ! getcache
+	then
+	    cat >"${tempsrc}" <<END
 #define _XOPEN_SOURCE ${xopen:-1}
 #include "${configh}"
 #include <sys/resource.h>
 int main() { return RLIMIT_${i} == RLIMIT_AS; getrlimit(RLIMIT_${i}, 0); }
 END
-		trymake && tryexec
-	    fi
+	    trymake && tryexec
+	fi
+	checked
+	if [ x"${checkresult}" = x"yes" ]
 	then
 	    defconfigh "HAVE_RLIMIT_${i}"
 	fi
-	checked
     done
 fi
 
+
 # check if ctags/etags accepts the --recurse option
 checking "if ctags accepts --recurse option"
-if checkby ctags --recurse -f /dev/null /dev/null
+checkby ctags --recurse -f /dev/null /dev/null
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     ctags_args='--recurse'
 else
     ctags_args='*.[ch]'
 fi
-checked
 checking "if etags accepts --recurse option"
-if checkby etags --recurse -o /dev/null /dev/null >/dev/null 2>&1
+checkby etags --recurse -o /dev/null /dev/null >/dev/null 2>&1
+checked
+if [ x"${checkresult}" = x"yes" ]
 then
     etags_args='--recurse'
 else
     etags_args='*.[ch]'
 fi
-checked
 
 
 if [ -n "${builtin_objs}" ]
