yash: share/completion/_blocksize: REFACTOR 	+completion//prefixdigits 	+completion//completesizesuffix yash: share/completion/split: -b, -C の補完で GNU/FreeBSD の拡張に対応
git-svn-id: svn+ssh://svn.sourceforge.jp/svnroot/yash/yash/trunk@2349 048f04df-13f5-43d7-8114-9f9ceecaec24

diff --git a/share/completion/_blocksize b/share/completion/_blocksize
--- a/share/completion/_blocksize
+++ b/share/completion/_blocksize
@@ -1,10 +1,11 @@
 # (C) 2010 magicant
 
-# This file contains a function that completes the argument to the --block-size
-# option of the df, du, and ls commands.
+# This file contains functions that help completion of file size suffixes.
 
 
-function completion//completeblocksize {
+# Modifies the $PREFIX variable to include argument digits.
+# If $TARGETWORD does not start with a digit, a non-zero status is returned.
+function completion//prefixdigits {
 	typeset word="${TARGETWORD#"$PREFIX"}"
 	word=${word#\'}
 	case $word in
@@ -13,33 +14,66 @@ function completion//completeblocksize {
 			word=${word#[[:digit:]]}
 		done
 		PREFIX=${TARGETWORD%"$word"}
+		return 0
 		;;
 	(*)
 		PREFIX=${TARGETWORD%"$word"}
-		#>>#
-		complete -P "$PREFIX" -D "print size using K, M, etc. for 1024^n" human-readable
-		complete -P "$PREFIX" -D "print size using k, M, etc. for 1000^n" si
-		#<<#
+		return 1
 		;;
 	esac
-	#>>#
-	complete -P "$PREFIX" -D "1024 bytes"   K
-	complete -P "$PREFIX" -D "1000 bytes"   KB
-	complete -P "$PREFIX" -D "1024^2 bytes" M
-	complete -P "$PREFIX" -D "1000^2 bytes" MB
-	complete -P "$PREFIX" -D "1024^3 bytes" G
-	complete -P "$PREFIX" -D "1000^3 bytes" GB
-	complete -P "$PREFIX" -D "1024^4 bytes" T
-	complete -P "$PREFIX" -D "1000^4 bytes" TB
-	complete -P "$PREFIX" -D "1024^5 bytes" P
-	complete -P "$PREFIX" -D "1000^5 bytes" PB
-	complete -P "$PREFIX" -D "1024^6 bytes" E
-	complete -P "$PREFIX" -D "1000^6 bytes" EB
-	complete -P "$PREFIX" -D "1024^7 bytes" Z
-	complete -P "$PREFIX" -D "1000^7 bytes" ZB
-	complete -P "$PREFIX" -D "1024^8 bytes" Y
-	complete -P "$PREFIX" -D "1000^8 bytes" YB
-	#<<#
+}
+
+# Completes file size suffixes specified in arguments according to the current
+# $TARGETWORD and $PREFIX.
+function completion//completesizesuffix {
+	typeset arg
+	for arg do
+		case $arg in
+		(b) #>>#
+			complete -P "$PREFIX" -D "512 bytes"    b
+			;; #<<#
+		(k) #>>#
+			complete -P "$PREFIX" -D "1024 bytes"   k
+			;; #<<#
+		(m) #>>#
+			complete -P "$PREFIX" -D "1024^2 bytes" m
+			;; #<<#
+		(g) #>>#
+			complete -P "$PREFIX" -D "1024^3 bytes" g
+			;; #<<#
+		(GNU*) #>>#
+			complete -P "$PREFIX" -D "1024 bytes"   K
+			complete -P "$PREFIX" -D "1000 bytes"   KB
+			complete -P "$PREFIX" -D "1024^2 bytes" M
+			complete -P "$PREFIX" -D "1000^2 bytes" MB
+			complete -P "$PREFIX" -D "1024^3 bytes" G
+			complete -P "$PREFIX" -D "1000^3 bytes" GB
+			complete -P "$PREFIX" -D "1024^4 bytes" T
+			complete -P "$PREFIX" -D "1000^4 bytes" TB
+			complete -P "$PREFIX" -D "1024^5 bytes" P
+			complete -P "$PREFIX" -D "1000^5 bytes" PB
+			complete -P "$PREFIX" -D "1024^7 bytes" Z
+			complete -P "$PREFIX" -D "1000^7 bytes" ZB
+			complete -P "$PREFIX" -D "1024^8 bytes" Y
+			complete -P "$PREFIX" -D "1000^8 bytes" YB
+			#<<#
+			if [ "$arg" != GNU-E ]; then #>>#
+				complete -P "$PREFIX" -D "1024^6 bytes" E
+				complete -P "$PREFIX" -D "1000^6 bytes" EB
+			fi #<<#
+			;;
+		esac
+	done
+	return 0
+}
+
+# Completes the argument to the --block-size option of df, du, and ls commands.
+function completion//completeblocksize {
+	if ! command -f completion//prefixdigits; then #>>#
+		complete -P "$PREFIX" -D "print size using K, M, etc. for 1024^n" human-readable
+		complete -P "$PREFIX" -D "print size using k, M, etc. for 1000^n" si
+	fi #<<#
+	command -f completion//completesizesuffix GNU
 }
 
 
